# Generated by Django 4.2.7 on 2025-05-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_investment_maturity_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='countdown_duration',
            field=models.IntegerField(default=5, help_text='Duration in days until investment matures after confirmation'),
        ),
    ]
