# Generated by Django 4.2.7 on 2025-05-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_investment_countdown_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralhistory',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referralhistory',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
